name: Build

on:
  pull_request:
    branches: [ develop ]

jobs:
       
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    outputs:
      get_current_tag: ${{ steps.set_current_tag_id.outputs.current_tag }}    
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: go build -o butler_go.exe -ldflags "-s -w" butler_go.go
            OUT_FILE_NAME: butler_go.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: ubuntu
            CMD_BUILD: go build -o butler_go butler_go.go
            OUT_FILE_NAME: butler_go
            ASSET_MIME: application/x-binary

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}          

      - name: Build with for ${{ matrix.TARGET }}
        run: ${{ matrix.CMD_BUILD }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.OUT_FILE_NAME }}
          path: ${{ matrix.OUT_FILE_NAME }}
          retention-days: 1

      - name: Set tag version to output
        id: set_current_tag_id
        run: echo "::set-output name=current_tag::${{ steps.tag_version.outputs.new_tag }}"          

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  telegram:
    runs-on: ubuntu-latest
    name: Notification
    needs: [ build ]

    steps:
      - name: Notify telegram message after Packaged
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>
            
            Commit with tag: ${{ needs.build.outputs.get_current_tag }}
            
            Repository: ${{ github.repository }}
           
            Branch: ${{ github.ref }}
            
            <b>Artifacts:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
